spring:
  application:
    name: ConnectHub
  # CHỈ ĐỊNH MÔI TRƯỜNG CHẠY MẶC ĐỊNH LÀ DEV (Khi ấn Run ở máy)
  profiles:
    active: dev

  threads:
    virtual:
      enabled: true
  jmx:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

bucket4j:
  enabled: false
  default-http-status-code: TOO_MANY_REQUESTS
  default-http-content-type: application/json;charset=UTF-8
  default-http-response-body: '{"status": 429, "error": "Too Many Requests", "message": "Bạn thao tác quá nhanh, vui lòng chờ trong giây lát trước khi thử lại."}'
  filters:
    - cache-name: rate-limit-buckets
      filter-method: servlet
      filter-order: -100
      url: ^/api/auth/.*
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 10
              time: 1
              unit: minutes
