spring:
  application:
    name: ConnectHub
  # CHỈ ĐỊNH MÔI TRƯỜNG CHẠY MẶC ĐỊNH LÀ DEV (Khi ấn Run ở máy)
  profiles:
    active: dev

  threads:
    virtual:
      enabled: true
  jmx:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

bucket4j:
  enabled: false
  default-http-status-code: TOO_MANY_REQUESTS
  default-http-content-type: application/json;charset=UTF-8
  default-http-response-body: '{"status": 429, "error": "Too Many Requests", "message": "Bạn thao tác quá nhanh, vui lòng chờ trong giây lát trước khi thử lại."}'
  filters:
    - cache-name: rate-limit-buckets
      filter-method: servlet
      filter-order: -100
      url: ^/api/auth/.*
      rate-limits:
        - cache-key: "getRemoteAddr()"
          bandwidths:
            - capacity: 10
              time: 1
              unit: minutes
server:
  port: ${PORT:10000}
  address: 0.0.0.0
  tomcat:
    # 1. Chỉ cho phép tối đa 200 request được xử lý cùng lúc (mặc định 8192 rất dễ sập RAM)
    max-connections: 200
    # 2. Số thread tối đa được tạo ra (giữ ở mức 50 để đỡ tốn CPU của Render)
    threads:
      max: 50
    # 3. Khi server bận, cho tối đa 100 request đứng xếp hàng (sau đó drop ngay lập tức)
    accept-count: 100
app:
  google:
    client-id: ${GOOGLE_CLIENT_ID}